5. Планирование – залог успеха
htmlacademy-yii/866299-task-force-1 pull request #4
Opened 2020-10-22 12:23 UTC by loktak

2020-10-23 12:49 UTC, Shv-sergey70 requested changes

2020-10-23 12:49 UTC, Shv-sergey70 commented on schema.sql
> +CREATE TABLE FilesToTask (
Обычно для именования полей используется snake_case
https://www.sqlstyle.guide/ru/#%D0%BE%D0%B1%D1%89%D0%B5%D0%B5

2020-10-23 12:49 UTC, Shv-sergey70 commented on schema.sql
> +    FileId INT UNSIGNED NOT NULL,
Поле не должно именоваться с большой буквы

2020-10-23 12:49 UTC, Shv-sergey70 commented on schema.sql
> +CREATE TABLE AvailableСategories (
А почему не просто `categories`?

2020-10-23 12:49 UTC, Shv-sergey70 commented on schema.sql
> +    FileTitle VARCHAR(128) NOT NULL
Не нужно отражать в названии колонок название сущности. То есть просто `path`, `title`

2020-10-23 12:49 UTC, Shv-sergey70 commented on schema.sql
> +CREATE TABLE AvailableSpecialization (
Почему не просто `specialization`?

2020-10-23 12:49 UTC, Shv-sergey70 commented on schema.sql
> +    NewFeedbackNotification BOOLEAN DEFAULT 1,
А что это за поля?

2020-10-23 13:47 UTC, loktak commented on schema.sql
> +CREATE TABLE FilesToTask (
Косяк, я тут просто подрабатывал и там требовали именно так нименовать

2020-10-23 13:49 UTC, loktak commented on schema.sql
> +    NewFeedbackNotification BOOLEAN DEFAULT 1,
Это поля
![image](https://user-images.githubusercontent.com/50331468/97011615-96b55d00-154f-11eb-877b-f19df3ac45c8.png)

Их можно в отдельную вынести сущность, Или это будет как-то по другому отслеживаться?

2020-10-23 14:11 UTC, Shv-sergey70 commented on schema.sql
> +    NewFeedbackNotification BOOLEAN DEFAULT 1,
Стоит все же вынести в отдельную сущность, так как таких свойств может быть очень много, и все хранить в таблице `users` не стоит

2020-10-24 12:04 UTC, Shv-sergey70 requested changes

2020-10-24 12:04 UTC, Shv-sergey70 commented on schema.sql
> +CREATE TABLE files_to_task (
Чем эта таблица отличается от `task_files`? Если это many-to-many, то оно здесь разве нужно? Ведь один документ - принадлежит только одной задаче. Но одна задача - многим документами

2020-10-24 12:04 UTC, Shv-sergey70 commented on schema.sql
> +CREATE TABLE portfolio_to_user (
Тут также нужно many-to-many?

2020-10-24 12:04 UTC, Shv-sergey70 commented on schema.sql
> +    user_id INT UNSIGNED NOT NUll,
А где первичный ключ?

2020-10-24 12:04 UTC, Shv-sergey70 commented on schema.sql
> +    user_who_id INT UNSIGNED NOT NULL,
`user_from_id`

2020-10-24 12:04 UTC, Shv-sergey70 commented on schema.sql
> +    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Что именно за `date`? Нужно раскрыть в названии

2020-10-24 12:04 UTC, Shv-sergey70 commented on schema.sql
> +    new_feedback_notification BOOLEAN DEFAULT 1,
Вряд ли стоит на уровне БД задавать значение по умолчанию = 1. Если в скором времени нужно будет поменять значение но 0, то придется менять структуру БД, выполняя миграцию.

2020-10-24 12:13 UTC, Shv-sergey70 commented on schema.sql
> +    category VARCHAR(128) NOT NULL,
Просто `name` или `title`, так как мы находимся в таблице `categories`

2020-10-24 12:13 UTC, Shv-sergey70 commented on schema.sql
> +    category_icon VARCHAR(128) NOT NULL
Можно просто `icon`, чтобы не дублировать название таблицы в названии поля

2020-10-24 12:13 UTC, Shv-sergey70 commented on schema.sql
> +    city VARCHAR(128) NOT NULL
`name` подойдет

2020-10-24 12:13 UTC, Shv-sergey70 commented on schema.sql
> +);
Если портфолио одно и одного юзера - то можно включить это поле в таблицу `users`. Так как по сути таблица состоит из 1 колонки

2020-10-24 12:13 UTC, Shv-sergey70 commented on schema.sql
> +    user_id INT UNSIGNED NOT NULL,
Можно не вводить дополнительный `id` как первичный ключ (ПК) и использовать `specialization_id`, `user_id` - как составной ПК
https://qna.habr.com/q/596547

2020-10-25 11:31 UTC, loktak commented on schema.sql
> +);
а если у пользователя несколько фоток работ?

2020-10-27 08:13 UTC, loktak commented on schema.sql
> +    user_id INT UNSIGNED NOT NULL,
`/*
Таблица содержит информацию о том какие специализации выбрали исполнители
*/
CREATE TABLE specialization_to_user (
	CONSTRAINT new_pk PRIMARY KEY (specialization_id, user_id),
    specialization_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    
    FOREIGN KEY (specialization_id) REFERENCES specializations (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);`

2020-10-27 08:15 UTC, loktak commented on schema.sql
> +    user_id INT UNSIGNED NOT NULL,
Если я правильно понял я могу добавлять новую строку и не переживать, что она будет повторяться?

2020-10-27 08:24 UTC, loktak commented on schema.sql
> +);
Я пока что добавил сюда еще user_id что бы сразу понимать чьё фото. с many to many я конечно перемудрил

2020-10-27 13:17 UTC, Shv-sergey70 commented on schema.sql
> +    user_id INT UNSIGNED NOT NULL,
Да, главное в таком случае, чтобы была уникальна связка из значений. 
То есть 
```
user_id  specialization_id
1            1
1            2
1            1 // не валидное значение
```

2020-10-27 13:20 UTC, Shv-sergey70 commented on schema.sql
> +    user_id INT UNSIGNED NOT NULL,
```
CREATE TABLE specialization_to_user (
    specialization_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,

    PRIMARY KEY (specialization_id, user_id)
    FOREIGN KEY (specialization_id) REFERENCES specializations (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);
```

2020-10-27 13:21 UTC, Shv-sergey70 commented on schema.sql
> +    user_id INT UNSIGNED NOT NULL,
И таблицу стоит назвать `user_specializations`
https://qna.habr.com/q/826687

2020-10-29 10:58 UTC, Shv-sergey70 commented on schema.sql
> +CREATE TABLE user_specialization (
`user_specializations`

2020-10-29 10:58 UTC, merged